### ISSUE TITLE
Using Persona

### ISSUE THREAD

**Issue by benbagley** [AdonisCommunity/adonis-blog-demo#24]
Hey all,

I'm trying to use [persona](https://github.com/adonisjs/adonis-persona) for authentication, however, I'm running into some issues, I got the user to register but I'm having issues doing the following.

- Verification link in the email, when clicked navigate back to the website to the login page (set `account_status` from **pending** to **active**)
- Resetting the user password, again link the email, when clicked navigate back to the website to the new password page.

I should be able to deal with the update profile etc but if you want to add this to the demo that would be great.

Spoken to @RomainLanz through Discord, no code needed for this issue.

**Comment by benbagley** [comment]
Any updates @RomainLanz

**Comment by RomainLanz** [comment]
I haven't the time to work on it.
Will try to update and all those feature before the end of the week.

**Comment by mguilhermetavares** [comment]
Any updates @RomainLanz

**Comment by RomainLanz** [comment]
Nope.

Do you struggle somewhere using `Persona`?
